{{- range $i, $v := (.Values.envFrom | default dict).secrets }}
{{- if $v.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic-deployment.name" $ }}-secret-env-{{ default $i $v.name }}
  labels:
    {{- include "basic-deployment.labels" $ | nindent 4 }}
type: Opaque
data:
{{- range $dk, $dv := $v.data }}
  {{ $dk }}: {{ $dv | toString | b64enc }}
{{- end }}
{{- end }}
{{- end }}
