annotations:
  category: Infrastructure
  images: |
    - name: memcached
      image: ghcr.io/adonaicosta/memcached:1.6.28-debian-12-r0
    - name: memcached-exporter
      image: ghcr.io/adonaicosta/memcached-exporter:0.14.3-debian-12-r8
    - name: os-shell
      image: ghcr.io/adonaicosta/os-shell:12-debian-12-r22
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.6.28
dependencies:
- name: common
  repository: https://adonaicosta.github.io/adonai-helm-charts
  tags:
  - common
  version: 2.x.x
description: Memcached is an high-performance, distributed memory object caching system,
  generic in nature, but intended for use in speeding up dynamic web applications
  by alleviating database load.
home: https://.com
icon: https://.com/assets/stacks/memcached/img/memcached-stack-220x234.png
keywords:
- memcached
- cache
maintainers:
- name: Adonai
  url: https://adonaicosta.github.io/adonai-helm-charts
name: memcached
sources:
- https://adonaicosta.github.io/adonai-helm-charts
version: 7.4.5
