createNamespace: false
config:
  clusters:
  - url: https://pve.ascsystem.com.br:8006/api2/json
    token_id: "csi@pve!csi"
    token_secret: "f7b9f717-8f20-411b-9056-0f653e600a6c"
    region: pvecl
metrics:
  enabled: true
nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
storageClass: []
#- name: proxmox
#  annotations:
#    storageclass.kubernetes.io/is-default-class: "true"
#  storage: isos
#  cache: none
#  reclaimPolicy: Delete
#  fstype: xfs
#  ssd: "true"
#   
