annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.20.1
description: A Library Helm Chart for grouping common logic between charts.
  This chart is not deployable by itself.
home: https://.com
icon: https://.com/downloads/logos/-mark.png
keywords:
- common
- helper
- template
- function
maintainers:
- name: ADonai
  url: https://adonaicosta.github.io/adonai-helm-charts
name: common
sources:
- https://adonaicosta.github.io/
type: library
version: 2.20.2
