annotations:
  category: DeveloperTools
  images: |
    - name: external-dns
      image: ghcr.io/adonaicosta/external-dns:0.15.0-debian-12-r4
  licenses: Apache-2.0
apiVersion: v2
appVersion: 0.15.0
dependencies:
- name: common
  repository: https://adonaicosta.github.io/adonai-helm-charts
  tags:
  - common
  version: 2.x.x
description: ExternalDNS is a Kubernetes addon that configures public DNS servers
  with information about exposed Kubernetes services to make them discoverable.
home: https://.com
icon: https://.com/assets/stacks/external-dns/img/external-dns-stack-220x234.png
keywords:
- external-dns
- network
- dns
maintainers:
- name: Adonai
  url: https://adonaicosta.github.io/adonai-helm-charts
name: external-dns
sources:
- https://adonaicosta.github.io/adonai-helm-charts
version: 8.5.1
