apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubesynca.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubesynca.labels" . | nindent 4 }}
data:
  {{- if .Values.config.kubeconfigContent }}
  kubeconfig: {{ .Values.config.kubeconfigContent | trim | b64enc | quote }}
  {{- end }}
